services:
  - type: web
    name: uno-server
    runtime: node
    plan: free
    buildCommand: npm ci && cd client && npm ci && cd ../server && npm ci && cd .. && npm run build
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
